- name: install the latest version of git
  yum:
    name: git
    state: latest
  become: yes
  become_user: root

- name: git clone TF devstack
  git:
    repo: https://github.com/tungstenfabric/tf-devstack.git
    dest: /home/centos/tf-devstack

- name: install k8s and tf
  command: "/home/centos/tf-devstack/k8s_manifests/startup.sh"
  environment:
    PATH: "/usr/local/bin:{{ lookup('env','PATH') }}"
    HOME: "{{ lookup('env','HOME') }}"
    CONTRAIL_CONTAINER_TAG: "{{ CONTRAIL_CONTAINER_TAG | default ('master-latest')}}"
  args:
    chdir: /home/centos/tf-devstack/k8s_manifests/

- name: Wait for kubectl to be ready
  command: "/usr/local/bin/kubectl get pods --all-namespaces"
  register: kubectl_ready
  until: kubectl_ready.rc == 0
  retries: 100
  delay: 15

- name: Wait for port 8082 to become open on the host
  wait_for:
    host: "{{ ansible_default_ipv4.address }}"
    port: 8082
    delay: 10
    timeout: 900
    state: started

- name: Test REST API
  uri:
    url: "http://{{ ansible_default_ipv4.address }}:8082/virtual-networks"
    method: GET
    remote_src: yes
  register: _result
  until: _result.status == 200
  retries: 120
  delay: 5
