- name: upgrade kernel
  yum: 
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - kernel-*
      - git

- name: restart server
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  become: true

- name: wait for server to come back online
  wait_for_connection:
    delay: 30
